DROP TABLE OFFERS;
DROP TABLE CAR;
DROP TABLE CUSTOMER;
DROP TABLE EMPLOYEE;



CREATE TABLE CAR(
CAR_ID INTEGER PRIMARY KEY,
MAKE VARCHAR2(50),
CAR_MODEL VARCHAR2(50),
COLOR VARCHAR2(50),
CAR_YEAR INTEGER,
CAR_COST NUMBER(*,2),
PURCHASE_STATUS VARCHAR(50) DEFAULT 'AVAILABLE',
CAR_OWNER VARCHAR(50)
);

CREATE TABLE CUSTOMER(
USERNAME VARCHAR2(50) PRIMARY KEY,
PASSWORD VARCHAR2(50),
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50),
CREDIT_SCORE INTEGER
);

CREATE TABLE EMPLOYEE(
EMP_ID INTEGER PRIMARY KEY,
FIRST_NAME VARCHAR2(50),
LAST_NAME VARCHAR2(50)
);

CREATE TABLE OFFERS(
OFFER_ID INTEGER PRIMARY KEY,
USERNAME VARCHAR2(50),
CAR_ID INTEGER,
CAR_COST NUMBER(*,2),
DOWN_PMT NUMBER(*,2),
LOAN_LENGTH INTEGER,
LOAN_BALANCE NUMBER(*,2),
ANN_EFF_RATE NUMBER(*,2),
MTHLY_PMT NUMBER(*,2),
PMT_LEFT INTEGER,
OFFER_STATUS VARCHAR(50)
);

--ADD CONSTRAINTS
ALTER TABLE OFFERS
ADD CONSTRAINT FK_OFFERS_CUSTOMER
FOREIGN KEY (USERNAME) REFERENCES CUSTOMER(USERNAME);

ALTER TABLE OFFERS
ADD CONSTRAINT FK2_OFFERS_CAR
FOREIGN KEY (CAR_ID) REFERENCES CAR(CAR_ID);

INSERT INTO OFFERS (OFFER_ID ,USERNAME, CAR_ID) VALUES(111233, 'KIDX', 2345);


-----------------------------------------------
SELECT USERNAME, PASSWORD FROM CUSTOMER WHERE USERNAME = 'kronos' AND PASSWORD = '1234';

SELECT * FROM CAR WHERE MAKE = 'Ford' AND CAR_ID = 123;

--CREATE TABLE ACCEPTEDOFFERS()
INSERT INTO CUSTOMER VALUES('kronos', '1234', 'JASON', 'STATHAM', 834);
INSERT INTO CAR VALUES(2345, 'HONDA', 'ACCORD', 'GRAY', 12364.23, 'AVAILABLE');
--INSERT INTO OFFERS (OFFER_ID ,USERNAME) VALUES(1202, 'KIDX');

ALTER TABLE CAR
ADD CAR_OWNER VARCHAR2(50);

ALTER TABLE OFFERS
ADD PMT_LEFT INTEGER;

UPDATE CAR SET CAR_OWNER = 'kronos' WHERE CAR_ID = 312;
